### ISSUE TITLE
[BUG] The OpenSearchCon banner is not responsive

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/project-website#3189] opened 2024-08-19 14:30 UTC
### Describe the bug

On mobile screens (of small width), the OpenSearchCon banner image on the opensearch.org site loses its proportions.

### Expected behavior

On mobile, part of the original image should be background for the banner and the text should be overlayed on top of the background image so that it's responsive.

### Screenshots

<img width="423" alt="Screenshot 2024-08-19 at 10 28 13 AM" src="https://github.com/user-attachments/assets/98bb2076-b35a-44dc-ab71-6032407cd900">

### To Reproduce

Open opensearch.org and look at the first banner that comes up.

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
All

**Comment by nateynateynate** [comment] 2024-08-20 16:56
Dupe of #2809, but thank you Fanit. If you have spare cycles and are able, feel free to propose a fix. I have a feeling there's some css that's forcing width and height when it doesn't need to be.

**Closed by nateynateynate** 2024-08-20 16:56 UTC
Labels: bug, untriaged
